// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity.Models;

public partial class BusTravelScheduleTbl
{
    public int BusDetailsId { get; set; }

    public int BusId { get; set; }

    public string Source { get; set; }

    public string Destination { get; set; }

    public int Fare { get; set; }

    public string DepatureDate { get; set; }

    public DateTime DepatureTime { get; set; }

    public bool Is_Deleted { get; set; }

    public DateTime Update_Time_Stamp { get; set; }

    public DateTime Create_Time_Stamp { get; set; }
}